
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "/home/ogu/workspace/prospector/zmk-config-prospector/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ogu/workspace/prospector/zmk-config-prospector/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/ogu/workspace/prospector/prospector-zmk-module/test/scanner_build_test/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ogu/workspace/prospector/prospector-zmk-module/test/scanner_build_test/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:8 (find_package)"
    message: |
      The target system is: Generic - 3.5.0 - arm
      The host system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/ogu/workspace/prospector/zmk-config-prospector/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ogu/workspace/prospector/zmk-config-prospector/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/ogu/workspace/prospector/prospector-zmk-module/test/scanner_build_test/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ogu/workspace/prospector/prospector-zmk-module/test/scanner_build_test/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:8 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /home/ogu/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      /home/ogu/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: /home/ogu/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/ogu/workspace/prospector/zmk-config-prospector/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ogu/workspace/prospector/zmk-config-prospector/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/ogu/workspace/prospector/prospector-zmk-module/test/scanner_build_test/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ogu/workspace/prospector/prospector-zmk-module/test/scanner_build_test/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:8 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /home/ogu/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        /home/ogu/workspace/prospector/zmk-config-prospector/build-adapter/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/ogu/workspace/prospector/zmk-config-prospector/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ogu/workspace/prospector/zmk-config-prospector/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/ogu/workspace/prospector/prospector-zmk-module/test/scanner_build_test/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ogu/workspace/prospector/prospector-zmk-module/test/scanner_build_test/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:8 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /home/ogu/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      /home/ogu/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: /home/ogu/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/ogu/workspace/prospector/zmk-config-prospector/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ogu/workspace/prospector/zmk-config-prospector/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/ogu/workspace/prospector/prospector-zmk-module/test/scanner_build_test/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ogu/workspace/prospector/prospector-zmk-module/test/scanner_build_test/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:8 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /home/ogu/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++ 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is GNU, found in:
        /home/ogu/workspace/prospector/zmk-config-prospector/build-adapter/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1131 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/ogu/workspace/prospector/zmk-config-prospector/zephyr/cmake/modules/kernel.cmake:134 (enable_language)"
      - "/home/ogu/workspace/prospector/zmk-config-prospector/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/ogu/workspace/prospector/prospector-zmk-module/test/scanner_build_test/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ogu/workspace/prospector/prospector-zmk-module/test/scanner_build_test/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:8 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      arm-zephyr-eabi-gcc (Zephyr SDK 0.16.5) 12.2.0
      Copyright (C) 2022 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...
